name: Static Analysis

on: [pull_request, push]

jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install --no-scripts

      - name: Run Larastan
        run: vendor/bin/phpstan analyse
