name: Static Analysis

on: [pull_request, push]

jobs:
  larastan:
    name: Run Larastan
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install --no-scripts

      - name: Run Larastan
        run: vendor/bin/phpstan analyse
